server:
  port: 15000

spring:
  application:
    name: spring-boot-admin
  security:
    user:
      name: "admin"
      password: "123123"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: admin
      user.password: 123123
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:123123@eureka1.wangxin.com:10001/eureka/,http://admin:123123@eureka2.wangxin.com:10002/eureka/,http://admin:123123@eureka3.wangxin.com:10003/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


